### ISSUE TITLE
TPI選択手法の考案

### ISSUE THREAD

**Issue by MaineK00n** [ehimetakahashilab/Renesas-TPI#15]
## WHY
- 選択手法によって性能が左右されるので，もう少し考える

## WHAT
- 何種類かサーベイしたり，考えたりする
- 最終的には実装して評価する

**Comment by Aono082** [comment]
![スクリーンショット (27)](https://user-images.githubusercontent.com/52318817/66800958-44ac2580-ef52-11e9-87a0-06fbc2c0275f.png)

[Embedded Deterministic Test Points.pdf](https://github.com/ehimetakahashilab/Renesas-TPI/files/3727403/Embedded.Deterministic.Test.Points.pdf)
