### ISSUE TITLE
COP再計算が終了しない

### ISSUE THREAD

**Issue by Aono082** [ehimetakahashilab/Renesas-TPI#30]
## WHY
再計算に失敗する

## WHAT
再計算を見直す

## REF
Error case
- s13207回路 信号線:8720

**Comment by Aono082** [comment]
./rtpi -n 2 s27
11
22
21
12
13
14
14
16
16
25
24
23
25
24
23
15
10
15
10

s27回路のTP11の時の伝搬経路
同じゲートをたどっているのが気になる。
push時にそのゲートがキュー内にあれば入れないという操作をやりたい

**Comment by Aono082** [comment]
unique_pushてのがあるねw
これでええんか

**Comment by Aono082** [comment]
とりあえず全部の回路で動いた
できたっぽい

**Comment by MaineK00n** [comment]
> push時にそのゲートがキュー内にあれば入れないという操作をやりたい

`unique_push`です
動いてよかったです

**Comment by MaineK00n** [comment]
PRもらえると助かります
