### ISSUE TITLE
挿入箇所が悪いと思われるTPを調べる

### ISSUE THREAD

**Issue by Aono082** [ehimetakahashilab/Renesas-TPI#34]
## WHY
TP挿入アルゴリズムを改良したい

## WHAT
選定したTPに対して簡単な構造解析による評価を行う

**Comment by MaineK00n** [comment]
TPに対して，どういった構造解析を行うか？

**Comment by Aono082** [comment]
選んだTPに対して、TPのレベル、出力コーン内のゲート数、出力コーン内のゲートのブランチがもつ総数みたいなのを数える
各TPのこれらの特性が似ている場合は、制御影響が衝突してる可能性が高い

**Comment by MaineK00n** [comment]
ゲート名(信号線番号)は考慮しない？

**Comment by Aono082** [comment]
詳しく見たくなったら、考える
とりあえずは考慮しないかな
